version: '3'

services:
  api:
    container_name: api-clicksul
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
    tty: true
    networks:
      - default

networks:
  default:
    driver: bridge

